### PR TITLE
Test PR checks

### PR DESCRIPTION
**Pull request by embeddedt**

### CODE REVIEW

**Comment by kisvegabor** [comment]
FYI, the automatic update of on release is working very well for `lv_sim_eclipse_sdl`. Only a [confdef.txt](https://github.com/lvgl/lv_sim_eclipse_sdl/blob/master/confdef.txt) neesd to be added and the release script will craete new lv_conf.h and change the listed defines.

We can add it to this, codeblocks or any other projects too.

**Comment by embeddedt** [comment]
I see no problem with adding it here. CodeBlocks will still need to be updated manually (or have a custom script written) as it does not refresh its view of the folders automatically.

**Comment by kisvegabor** [comment]
Eclipse also needs an extra refresh, but I think it's much better than having older versions.

Let me know if you added the configs and I'll update the release script.

**Comment by embeddedt** [comment]
Is there a reason why we can't use a stub `lv_conf.h` file instead, with only the required defines? `lv_conf_internal.h` appears to automatically define all the default values if they are not present.

**Comment by kisvegabor** [comment]
It'd be possible. However, I think it's important for people to see all the options in one place.

**Comment by embeddedt** [comment]
True; I didn't think of that. Alright; I will add a `confdef.txt` file on the weekend.

**Comment by embeddedt** [comment]
@kisvegabor I've added `confdef.txt`, but I'm not sure how to go about testing it.

**Comment by kisvegabor** [comment]
It's part of the release script so it can't be run separately. 

I was thinking about adding release scripts to every project but it'd be duplication in every project. 

So now it looks like this:
1. lvgl, lv_examples, lv_drivers are released from `master`. (tag, merge to release branches)
2. Projects ar updated from the release branches
3. Merge `dev` to `master`.

What should we change to make the live examples work?

**Pull request closed without merging**
